import gradientBg from '../assets/gradient-bg.png';

// COLORS
const MAIN_COLOR_LIGHT = '#fff';
const MAIN_COLOR_DARK = '#2D3748';
const LIGHT_COLOR = '#EDF2F7';
const LABEL_COLOR = '#4A5568';
const PLACEHOLDER_COLOR = '#A0AEC0';
const BUTTON_BLUE_BG_COLOR = '#667EEA';
const SUBTITLE_COLOR = '#AAFAFF';
const BORDER_COLOR = '#CBD5E0';
const GRAY_COLOR = '#718096';

// GRADIENT BG
const GRADIENT_BACKGROUND_DESKTOP = `background: url(${gradientBg}), linear-gradient(180deg, #A0AEC0 0%, #718096 100%);`;
const GRADIENT_BACKGROUND_MOBILE = 'background: linear-gradient(180deg, #a0aec0 0%, #718096 100%);';

// RADIUS
const BORDER_RADIUS_10 = '10px';
const BORDER_RADIUS_4 = '4px';

// SIZES
const DESKTOP_FONT_SIZE_64 = '64px';
const DESKTOP_FONT_SIZE_30 = '30px';
const DESKTOP_FONT_SIZE_20 = '20px';
const DESKTOP_FONT_SIZE_18 = '18px';
const DESKTOP_FONT_SIZE_16 = '16px';
const DESKTOP_FONT_SIZE_14 = '14px';
const MOBILE_FONT_SIZE_48 = '48px';
const MOBILE_FONT_SIZE_24 = '24px';

export {
  MAIN_COLOR_LIGHT,
  MAIN_COLOR_DARK,
  LIGHT_COLOR,
  LABEL_COLOR,
  BUTTON_BLUE_BG_COLOR,
  SUBTITLE_COLOR,
  BORDER_COLOR,
  DESKTOP_FONT_SIZE_64,
  DESKTOP_FONT_SIZE_30,
  DESKTOP_FONT_SIZE_20,
  DESKTOP_FONT_SIZE_18,
  DESKTOP_FONT_SIZE_16,
  DESKTOP_FONT_SIZE_14,
  MOBILE_FONT_SIZE_48,
  MOBILE_FONT_SIZE_24,
  BORDER_RADIUS_10,
  BORDER_RADIUS_4,
  GRADIENT_BACKGROUND_DESKTOP,
  GRADIENT_BACKGROUND_MOBILE,
  PLACEHOLDER_COLOR,
  GRAY_COLOR,
};
